### ISSUE TITLE
Source code installation failing with error during make: 'Rcpp_eval' is not a member of 'Rcpp'

### ISSUE THREAD

**Issue by tushu1232** [vertica/DistributedR#2]
Hello I am following the installation document provided in the source code and trying to compile it on CentOS but getting and error mentioned in the subject.Is there a fix for it.

[root@quickstart DistributedR-master]# cat /etc/redhat-release 
CentOS release 6.4 (Final)

[root@quickstart DistributedR-master]# uname -ar
Linux quickstart.cloudera 2.6.32-358.el6.x86_64

Creating a generic function for 'ncol' from package 'base' in package 'distributedR'
Creating a generic function for 'NCOL' from package 'base' in package 'distributedR'
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
* DONE (distributedR)
g++ platform/executor/src/Rtools.cpp -c -g -O2 -fopenmp -finline-limit=10000 -DNDEBUG -DBOOST_LOG_DYN_LINK -DCSTACK_DEFNS -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I /home/cloudera/Downloads/DistributedR-master/third_party/install/include -I /home/cloudera/Downloads/DistributedR-master/platform/messaging/gen-cpp -I /home/cloudera/Downloads/DistributedR-master/third_party/boost_threadpool/threadpool -I /home/cloudera/Downloads/DistributedR-master/third_party/atomicio -I platform/common `/usr/lib64/R/bin/R CMD config --cppflags` `Rscript -e "Rcpp:::CxxFlags()"` `Rscript -e "RInside:::CxxFlags()"` -lm -rdynamic -L /home/cloudera/Downloads/DistributedR-master/lib -Wl,-rpath,/home/cloudera/Downloads/DistributedR-master/lib `/usr/lib64/R/bin/R CMD config --ldflags` -lpthread -L/home/cloudera/Downloads/DistributedR-master/third_party/install/lib -Wl,-rpath,/home/cloudera/Downloads/DistributedR-master/third_party/install/lib -lboost_thread -lboost_system -lboost_log -lboost_log_setup -lboost_chrono -L /home/cloudera/Downloads/DistributedR-master/third_party/atomicio -Wl,-rpath,/home/cloudera/Downloads/DistributedR-master/third_party/atomicio -latomicio `Rscript -e "Rcpp:::LdFlags()"` `Rscript -e "RInside:::LdFlags()"` -laio -lrt -Wno-deprecated-declarations -DSTRICT_R_HEADERS          -fPIC -o platform/executor/src/Rtools.o
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
g++ platform/executor/src/executor.cpp -c -g -O2 -fopenmp -finline-limit=10000 -DNDEBUG -DBOOST_LOG_DYN_LINK -DCSTACK_DEFNS -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I /home/cloudera/Downloads/DistributedR-master/third_party/install/include -I /home/cloudera/Downloads/DistributedR-master/platform/messaging/gen-cpp -I /home/cloudera/Downloads/DistributedR-master/third_party/boost_threadpool/threadpool -I /home/cloudera/Downloads/DistributedR-master/third_party/atomicio -I platform/common `/usr/lib64/R/bin/R CMD config --cppflags` `Rscript -e "Rcpp:::CxxFlags()"` `Rscript -e "RInside:::CxxFlags()"` -lm -rdynamic -L /home/cloudera/Downloads/DistributedR-master/lib -Wl,-rpath,/home/cloudera/Downloads/DistributedR-master/lib `/usr/lib64/R/bin/R CMD config --ldflags` -lpthread -L/home/cloudera/Downloads/DistributedR-master/third_party/install/lib -Wl,-rpath,/home/cloudera/Downloads/DistributedR-master/third_party/install/lib -lboost_thread -lboost_system -lboost_log -lboost_log_setup -lboost_chrono -L /home/cloudera/Downloads/DistributedR-master/third_party/atomicio -Wl,-rpath,/home/cloudera/Downloads/DistributedR-master/third_party/atomicio -latomicio `Rscript -e "Rcpp:::LdFlags()"` `Rscript -e "RInside:::LdFlags()"` -laio -lrt -Wno-deprecated-declarations -DSTRICT_R_HEADERS          -fPIC -o platform/executor/src/executor.o
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
In file included from /usr/lib64/R/library/RInside/include/RInside.h:26,
                 from platform/executor/src/executor.cpp:49:
/usr/lib64/R/library/RInside/include/RInsideCommon.h:49:1: warning: "CSTACK_DEFNS" redefined
<command-line>: warning: this is the location of the previous definition
platform/executor/src/executor.cpp: In function 'int main(int, char**)':
platform/executor/src/executor.cpp:661: error: 'Rcpp_eval' is not a member of 'Rcpp'
make: *** [platform/executor/src/executor.o] Error 1

**Comment by shreya2k7** [comment]
Hi,
Thanks for trying out Distributed R. The error comes because of in-compatible versions Rcpp and RInside installed. I presume, you installed Rcpp version 0.10.6 and RInside version 0.2.10 as was available in the third_party/ folder.

We have now updated the third_party/ folder with compatible version of Rcpp (version 0.11.2) and RInside (version 0.2.11). Please install these packages before trying to build Distributed R again.
Also, please make sure that you have cleaned up Distributed R build by issuing 'make distclean' on trunk before you try to build Distributed R again. 

Thanks,
Shreya

**Comment by fun-indra** [comment]
We also provide pre-built binaries that are easy to install.
Binaries can be accessed at: http://www.vertica.com/hp-vertica-products/hp-vertica-distributed-r/

Thanks,
Indrajit
