### ISSUE TITLE
 A <- darray(dim=c(9,9), blocks=c(3,3), sparse=FALSE, data=10) stuck R

### ISSUE THREAD

**Issue by armgong** [vertica/DistributedR#4]
2015-Feb-05 05:10:54.290356 [DEBUG] New Update pointer to maintain list of updated split/composite variables in Function execution created.
2015-Feb-05 05:10:54.290439 [INFO] *** No Task under execution. Waiting from Task from Worker **
2015-Feb-05 05:11:11.942543 [DEBUG] Number of Split variables: 1
2015-Feb-05 05:11:11.942623 [DEBUG] Read Split Variable R-shm-50437-2011658264_0_0 (dhs in R)
2015-Feb-05 05:11:11.942818 [DEBUG] ParseShm: Uninited array R-shm-50437-2011658264_0_0 (this should only happen at array creation)
2015-Feb-05 05:11:11.942905 [INFO] New Task received from Worker. Reading Function Arguments and Body
2015-Feb-05 05:11:11.942940 [DEBUG] Reading Raw Arguments of Function from Worker and load it in R-session
2015-Feb-05 05:11:11.942971 [DEBUG] Number of Raw variables: 5
2015-Feb-05 05:11:11.942999 [DEBUG] Read Raw variable val

it is seems following code cause this issue

int ReadRawArgs(RInside& R) {  // NOLINT
  LOG_DEBUG("Reading Raw Arguments of Function from Worker and load it in R-session");
  int raw_vars;  // number of non-split variables
  Timer timer;
  timer.start();
  int res = scanf(" %d ", &raw_vars);
  if (res != 1) {
    LOG_WARN("ReadRawArgs => Bad file format for Executor. Executor cannot recognize commands from Worker.");
    throw PrestoWarningException
      ("ReadRawArgs::Executor cannot recognize commands from a worker");
  }

  LOG_DEBUG("Number of Raw variables: %d", raw_vars);

  for (int i = 0; i < raw_vars; i++) {
    char name[256];
    int size;
    res = scanf(" %s %d:", name, &size); //**************************stuck here,but don't know why
    LOG_DEBUG("Read Raw variable %s", name);
    if (res != 2) {
      LOG_WARN("ReadRawArgs => Variable %s - Bad file format for Executor. Executor cannot recognize commands from Worker.", name);
      throw PrestoWarningException
        ("ReadRawArgs::Executor cannot recognize commands from a worker");
    }

**Comment by etduwx** [comment]
Hi,

This *may* be due to a gcc(version >= 4.8) compilation issue. We are currently investigating it.

Thanks,
Edward
